[FY-10373] Add POST workflow route in doc
spotinst/openapi pull request #636
Opened 2024-07-11 10:26 UTC by kabrashubham

# Jira Ticket

[FY-10373](https://spotinst.atlassian.net/browse/FY-10373)

# Demo

![image](https://github.com/spotinst/openapi/assets/45758574/3dd88493-ae82-4cf3-a99d-e516280a645d)

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-07-15 16:15 UTC, xiaoyzhu requested changes

2024-07-15 16:15 UTC, xiaoyzhu commented on api/services/connect/workflows/paths/index.yaml
> +  summary: Create a new workflow by creating a new SSM automation document in AWS
No need to mention the details about SSM document in the public API doc.
```suggestion
  summary: Create a new workflow in the selected workspace.
```

2024-07-16 03:15 UTC, shubhamhapse approved these changes

2024-07-17 04:37 UTC, xiaoyzhu approved these changes
LGTM.

2024-07-17 04:40 UTC, merged