Update workspace_api for OpenAPI
spotinst/openapi pull request #659
Opened 2024-09-24 12:24 UTC by kabrashubham

# Jira Ticket

[FY-10199](https://spotinst.atlassian.net/browse/FY-10199)

# Demo

![image](https://github.com/user-attachments/assets/404ca07f-5580-4b9b-88be-489735c538f0)
![image](https://github.com/user-attachments/assets/34d43f1f-d98c-4f10-b74e-2f639adf9a28)
![image](https://github.com/user-attachments/assets/e2f8c316-ecc9-46a0-902d-25de2138ac24)
![image](https://github.com/user-attachments/assets/1dec31c4-cbc1-4fd0-9f82-09cc6c0fd61e)
![image](https://github.com/user-attachments/assets/5a87533f-735f-45c3-8ad8-0fe659dfbf32)
![image](https://github.com/user-attachments/assets/d1d3ee98-d63e-47f5-b351-5256424030f7)
![image](https://github.com/user-attachments/assets/c5647fc2-f5f1-48d7-92c8-464b1b74e975)
![image](https://github.com/user-attachments/assets/a87f0d54-5409-49b5-92e4-4d45757aa86d)

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-09-25 08:32 UTC, kabrashubham commented
Updated - 
![image](https://github.com/user-attachments/assets/5b748372-ad4a-4768-8cdb-8db62cd93306)

2024-09-26 18:45 UTC, xiaoyzhu requested changes

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/EntityBlock.yaml
> +    description: Spot id of the user
Use `ID` instead of `id` for consistency with the current convention.
```suggestion
    description: Spot ID of the user
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/MoveOrder.yaml
> +    description: If we need to move all integration used in that workflow
```suggestion
    description: If we need to move all integrations used in that workflow
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/MoveOrder.yaml
> +    description: Workflow name to move in new workspace
```suggestion
    description: Name of the workflow to move to the new workspace
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/MoveOrder.yaml
> +    description: Workspace id to move the workflow into
```suggestion
    description: Workspace ID to move the workflow into
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/WorkspaceCommon.yaml
> +    description: Description about workspace
```suggestion
    description: Description of workspace
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/WorkspaceCommonID.yaml
> +      description: Unique workspace id
```suggestion
      description: Unique workspace ID
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/WorkspaceNameAvailabilityResponse.yaml
> +      description: Check if workspace name is available or not
```suggestion
      description: Check if workspace name is available for use
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/schemas/WorkspaceResponse.yaml
> +      description: Unique workspace id
```suggestion
      description: Unique workspace ID
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/index.yaml
> +  description: List all Workspaces the user is authorized to view.
```suggestion
  description: List all workspaces the user is authorized to view.
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/move-order.yaml
> +  description: "It moves all integrations used in workflow and workflow itself\nin
```suggestion
  description: "It moves a workflow and all integrations it uses \nto a
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_id.yaml
> +  description: Delete a specific Workspace identified by workspace_id
```suggestion
  description: Delete a workspace specified by workspace_id
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_id.yaml
> +  description: Get a specific Workspace details using workspace_id.
```suggestion
  description: Get details of a workspace specified by workspace_id.
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_id.yaml
> +  summary: Get Workspace by Id
```suggestion
  summary: Get Workspace by ID
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_id.yaml
> +  description: Update the given Workspace.
```suggestion
  description: Update a workspace specified by workspace_id.
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_name.yaml
> +  summary: Workspace by Name
```suggestion
  summary: Get Workspace by Name
```

2024-09-26 18:45 UTC, xiaoyzhu commented on api/services/connect/workspaces/paths/workspace_name.yaml
> +  description: Get a specific Workspace using Workspace Name.
```suggestion
  description: Get details of a specific workspace using workspace name.
```

2024-09-27 21:58 UTC, xiaoyzhu approved these changes
LGTM.

2024-09-27 21:59 UTC, merged