SF-18880 - add Cost Intelligence 'Setup CI on Spot account' related API endpoints.
spotinst/openapi pull request #673
Opened 2024-11-19 22:07 UTC by paul-van-wichen

2024-11-20 20:17 UTC, sc0tt-sullivan approved these changes

2024-12-09 15:27 UTC, TamirYaariSpot requested changes

2024-12-09 22:07 UTC, paul-van-wichen commented on api/services/beci/setup/paths/cbiV1SetupAccountValidation.yaml
> +  summary: Perform Cost Intelligence setup validations
Updated.

2024-12-09 22:07 UTC, paul-van-wichen commented on api/services/beci/setup/paths/cbiV1SetupAccount.yaml
> +  summary: Get Cost Intelligence registered accounts
Updated.

2024-12-09 22:52 UTC, paul-van-wichen commented
Replaced by https://github.com/spotinst/openapi/pull/689

2024-12-09 22:52 UTC, closed without merging