Add Docs For secops rest apis
spotinst/openapi pull request #687
Opened 2024-12-09 05:16 UTC by abharti1111

# Jira Ticket
_[DOC-2163](https://spotinst.atlassian.net/browse/DOC-2163)_

# Demo

https://github.com/user-attachments/assets/c5bcefba-32dd-4078-9541-7eda8a5a6ab3

# Checklist:
- [x] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [x] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have validated all the requirements in the Jira task were answered
- [x] I have all neccessary approvals for the design/mini design of this task
- [x] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-12-09 07:02 UTC, RachelHooley requested changes

2024-12-09 07:02 UTC, RachelHooley commented on api/services/security/v1/schemas/MisconfigurationWhereModel.yaml
line 16: A comma-separated list of cloud resources
(missing _s_ at the end)

2024-12-09 11:35 UTC, RachelHooley approved these changes

2024-12-10 07:09 UTC, TamirYaariSpot approved these changes

2024-12-10 07:11 UTC, merged